// BUILDINGS
export const BUILDING_REQUEST_START = "BUILDING_REQUEST_START";
export const BUILDING_REQUEST_FAIL = "BUILDING_REQUEST_FAIL";

export const FETCH_BUILDINGS_SUCCESS = "FETCH_BUILDINGS_SUCCESS";
export const ADD_BUILDING_SUCCESS = "ADD_BUILDING_SUCCESS";
export const UPDATE_BUILDING_SUCCESS = "UPDATE_BUILDING_SUCCESS";
export const DELETE_BUILDING_SUCCESS = "DELETE_BUILDING_SUCCESS";

export const SELECT_BUILDING = "SELECT_BUILDING";

// ROOMS
export const ROOM_REQUEST_START = "ROOM_REQUEST_START";
export const ROOM_REQUEST_FAIL = "ROOM_REQUEST_FAIL";

export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const ADD_ROOM_SUCCESS = "ADD_ROOM_SUCCESS";
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";

export const SELECT_ROOM = "SELECT_ROOM";

// DEVICES
export const DEVICE_REQUEST_START = "DEVICE_REQUEST_START";
export const DEVICE_REQUEST_FAIL = "DEVICE_REQUEST_FAIL";

export const FETCH_DEVICES_SUCCESS = "FETCH_DEVICES_SUCCESS";
export const FETCH_ALL_DEVICES_ID_SUCCESS = "FETCH_ALL_DEVICES_ID_SUCCESS";
export const ADD_DEVICE_SUCCESS = "ADD_DEVICE_SUCCESS";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
export const DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";

export const SET_DEVICES_TO_NULL = "SET_DEVICES_TO_NULL";

// AWS DEVICES
export const SET_AWS_DEVICE_DATA = "SET_AWS_DEVICE_DATA";

// USER
export const USER_REQUEST_START = "USER_REQUEST_START";
export const USER_REQUEST_FAIL = "USER_REQUEST_FAIL";

export const SET_IS_ADMIN = "SET_IS_ADMIN";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_IS_REQUESTING = "SET_IS_REQUESTING";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";